#!/bin/bash

# Script à créer directement sur le VPS
echo "Création d'un script à taper directement sur le VPS..."

echo "Copiez et collez ces commandes DIRECTEMENT sur le VPS:"
echo ""
echo "# =========================================="
echo "# COMMANDES À COLLER SUR LE VPS"
echo "# =========================================="
echo ""
echo "cat > /tmp/deploy-clone.sh << 'EOF'"
echo "#!/bin/bash"
echo ""
echo "echo 'Déploiement par clonage GitHub...'"
echo ""
echo "# Arrêter PM2"
echo "pm2 stop tomati-production"
echo ""
echo "# Sauvegarde"
echo "mv /home/tomati/tomati-market /home/tomati/backup-\$(date +%H%M%S) 2>/dev/null"
echo ""
echo "# Cloner depuis GitHub"
echo "git clone https://github.com/imen-nasrii/cool-mobile-spark.git /home/tomati/tomati-market"
echo ""
echo "# Configuration"
echo "cd /home/tomati/tomati-market"
echo ""
echo "cat > .env << 'ENVEOF'"
echo "NODE_ENV=production"
echo "PORT=5000"
echo "DATABASE_URL=postgresql://tomati:Tomati123@localhost:5432/tomati_market"
echo "PGHOST=localhost"
echo "PGPORT=5432"
echo "PGUSER=tomati"
echo "PGPASSWORD=Tomati123"
echo "PGDATABASE=tomati_market"
echo "ENVEOF"
echo ""
echo "# Installation et build"
echo "npm install --production"
echo "npm run db:push"
echo "npm run build"
echo ""
echo "# Redémarrage"
echo "pm2 restart tomati-production"
echo ""
echo "# Tests"
echo "pm2 status"
echo "curl -s http://localhost:5000/api/stats"
echo ""
echo "echo 'Déploiement terminé! App sur http://51.222.111.183'"
echo "EOF"
echo ""
echo "chmod +x /tmp/deploy-clone.sh"
echo "/tmp/deploy-clone.sh"
echo ""
echo "# =========================================="
echo "# FIN DES COMMANDES"
echo "# =========================================="