name: Build Tomati APK
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build React app
        run: npm run build
        
      - name: Sync Capacitor
        run: npx cap sync
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tomati-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          
      - name: Upload Debug APK
        run: |
          cd android
          ./gradlew assembleDebug
          
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tomati-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk